{% set name = "libdrs_f" %}
{% set version = "3.1.2" %}
{% set build = 112 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/libdrs/archive/v{{ version }}.tar.gz
  sha256: 90e10191116a78228739276078a0ddcf0d6458516f192e9e79fecb2beeceb3fa

build:
  number: {{ build }}
  skip: True  # [win]

requirements:

  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
    - g2clib
    - libcdms
    - libpng
    - libnetcdf
    - libnetcdf * nompi_*
  run:
    - g2clib
    - libcdms
    - libpng
    - libnetcdf

test:
  commands:
    - test -f $PREFIX/lib/libdrsfortran.a

about:
  home:  http://cdat.llnl.gov
  license: BSD-3-Clause
  license_file: bsd-3-clause.txt
  summary: 'Data Retrieval and Storage DRS software Fortran library'
  description: |
    libdrs is suitable for the data generated and used in climate model research.
    It is oriented toward use with models generating very large datasets on
    supercomputers, as well as with graphics workstations used for analysis and
    display of smaller subsets of data.
  dev_url: http://github.com/CDAT/libdrs

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - downiec
    - jasonb5
    - xylar
